---
- name: Install Tomcat Server
  hosts: all
  become: true

  tasks:
    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jre-headless

    - name: Download Apache Tomcat v9.0.55
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.tar.gz
        dest: /

    - name: Extract Apache Tomcat v9.0.55
      unarchive:
        src: /apache-tomcat-9.0.55.tar.gz
        dest: /
        remote_src: yes