pipeline {

   agent any

   stages {
      stage('Download Image from Docker Hub') {
         steps {
            sh 'docker pull brazdore/ilegra-cn-temafinal01:temafinal01'
         }
      }

      stage('Run Docker Image') {
         steps {
            sh 'docker run -p 8089:8080 -d brazdore/ilegra-cn-temafinal01:temafinal01'
         }
      }
   }
}